server:
  port: 80
  undertow:
    threads:
      io: 4
      worker: 50
  compression:
    enabled: true
  http2:
    enabled: true
  servlet:
    encoding:
      force: true
      charset: UTF-8

spring:
  application:
    name: backend-template-server-admin
  main:
    allow-bean-definition-overriding: true
  profiles:
    include:
      - security
      - openapi
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  web:
    resources:
      chain:
        compressed: true
      cache:
        cachecontrol:
          max-age: 216000
          must-revalidate: true
      static-locations: classpath:/static,classpath:/node_icon,classpath:/public,classpath:/resources,classpath:/META-INF/resources,file:${innospots.config.upload-file-path},classpath:/META-INF/resources/apps/visualization/
  servlet:
    multipart:
      max-file-size: 10MB
  jmx:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics,prometheus
  endpoint:
    health:
      show-details: NEVER
      probes:
        enabled: true
  health:
    elasticsearch:
      enabled: false
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true


logging:
  file:
    path: ${innospots.server.log-root-path}
  config: classpath:log4j2-spring.xml


mybatis-plus:
  global-config:
    banner: off
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

innospots:
  config:
    host: ${SERVER_HOST:http://localhost}:${server.port}
    schema-cache-timeout-second: 180
    extension-load: true
    public-key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCV0BmhCv/TVA6du/ku9kMuU7J6a1CZwwSyNUHHcDpnr0/FwJucEzcpwrkcI98uv2JVqSV+cf9BfyKAYc3pLOI6roVMNW7ah3i3sW0wKuLE00YjSsz3EbtCpxmg22+CruWFCDX3Jk0rkLiqNVTByppfEAzfMBHXS1nHstfBV+/TgQIDAQAB
    private-key: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAJXQGaEK/9NUDp27+S72Qy5TsnprUJnDBLI1QcdwOmevT8XAm5wTNynCuRwj3y6/YlWpJX5x/0F/IoBhzeks4jquhUw1btqHeLexbTAq4sTTRiNKzPcRu0KnGaDbb4Ku5YUINfcmTSuQuKo1VMHKml8QDN8wEddLWcey18FX79OBAgMBAAECgYEAgHCAeJRQjmLjgRIWac/R+xbgzpnQ6XLMROjp803hlOE1mEowXxgOVCxQvbJ3dsG4Uc6JiaW8fO+9qamwerfzX5tgjhc7ryqTHBE50Xe5ITJkLVt8BhTSvpNixG9CufBderhjY/Q1657NwYrbbTtCjZNKnVM842hAf/sX5Pwt+UECQQDv6LtVEx639BfPKRMqZVHHR2Apo48PRGAKd0alGU0mqAdSwgRuSHF3EdoKk+n6F4Z9wZTV1EWJ0P0XbmfpnrcZAkEAn9xnzG0JTAZDnnYE1nz2VhrWuQluyRDlp6Geof6rbtQKqRK8NJ4prI0le99NCJzeBXqYRNydX6rTRlx6SRMUqQJAJkTDjSCNp95B5gOxUPP0hYs3Ja03ZsILZ9/63t8YVXA8KtFUD5tyrgGk/Eb37bLO+0Rjz3Aa3478sD4mSTfOEQJANPkfeFFldEjbHWZ0YfMU2iGYp8ZlbMFpqKvY2kt+2YHwamhn73O90Y0QL8UmTMVWmTAvxxnoGGyOCFHav95PyQJBANquqvB2JC9AIHLkGfdl48fYDrM4W+l0Gp44/Q4xvBrRdrOq6+auV79LWjsi3A13hRF6Q7IK7A91kU/g1WRegS0=
    secret-key: Q2K9aOslSxDv3wM5
  store:
    store-mode: ${store_mode:LOCAL}
    store-file-path: .download_files/


  server:
    enable-registry: true
    # set system environment variable: logRootPath
    log-root-path: ${LOG_PATH:logs}
    watcher-size: 10
    # open debug mode
    debug-mode: true
    server-info:
      title: "Backend title"
      code: "backend-template"
      description: "Backend"
      favicon: "/images/favicon.png"
      logo: "/images/logo.png"
      indexPage: "/"
      loginPage: "/login"
      successPage: "/apps/visualization/workspace"
      authFailPage: "/403.html"
      auth-mode: ${auth_mode:BASIC}
#      auth-mode: OAUTH
      welcome-image: "/images/login_display.svg"
      slogan-title: "\\${system.welcome.slogan.title:Backend title}"
      slogan-content: "\\${system.welcome.slogan.content:Backend title}"

  workflow:
    execution-store-path: .execution_contexts
    script-build-path: .script_build_path
    retain-script-source: false

  db:
    driver-class-name: ${DB_DRIVER:com.mysql.cj.jdbc.Driver}
    jdbc-url: jdbc:mysql://${DB_IP}:${DB_PORT:3306}/${DB_NAME}?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=${DB_TIMEZONE:GMT%2B8}&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    maximum-pool-size: 64
    minimum-idle: 2
    pool-name: db-pool
    max-lifetime: 1800000
    idle-timeout: 600000 # millisecond,default ten minute


# /actuator/info config
info:
  build:
    version: ${java.version}
  profiles:
    active: ${spring.profiles.active}
