server:
  port: 8760

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    persist-authorization: true

spring:
  jpa:
    hibernate:
#      ddl-auto: none
      ddl-auto: validate
#      ddl-auto: update
    show-sql: true
    generate-ddl: false
